# Generated by Django 3.2.9 on 2021-11-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_table_feedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='feedback_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
