# Generated by Django 3.2.9 on 2021-11-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_table_feedback_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback_table',
            old_name='user_id',
            new_name='user',
        ),
    ]
