# Generated by Django 3.2.9 on 2021-12-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20211123_1526'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedbacks',
            table='feedbacks_table',
        ),
    ]
