# Generated by Django 3.2.9 on 2021-11-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_rename_customeruser_systemuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='systemuser',
            name='sex',
        ),
    ]
