# Generated by Django 3.2.9 on 2021-11-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('feedback', '0007_auto_20211123_1526'),
        ('login_register', '0004_auto_20211122_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemUser',
        ),
    ]
