# Generated by Django 3.2.9 on 2021-12-09 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_resources',
            fields=[
                ('resource_table_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_nums', models.IntegerField(default=0)),
                ('camera_nums', models.IntegerField(default=0)),
                ('video_nums', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_resources_table',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('camera_name', models.CharField(max_length=10)),
                ('used', models.BooleanField(default=False)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Camera_msg_table',
            },
        ),
    ]
