# Generated by Django 3.2.9 on 2021-12-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask_detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='desc',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
