# Generated by Django 3.2.9 on 2021-12-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask_detect', '0002_alter_camera_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_resources',
            name='video_nums',
            field=models.IntegerField(default=10),
        ),
    ]
