# Generated by Django 3.2.9 on 2021-12-09 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mask_detect', '0003_alter_user_resources_video_nums'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_resources',
            new_name='User_resources1',
        ),
    ]
