# Generated by Django 3.2.9 on 2021-12-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mask_detect', '0004_rename_user_resources_user_resources1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_resources1',
        ),
    ]
