# Generated by Django 3.2.9 on 2021-12-09 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mask_detect', '0005_delete_user_resources1'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_resources',
            fields=[
                ('resource_table_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_nums', models.IntegerField(default=0)),
                ('camera_nums', models.IntegerField(default=0)),
                ('video_nums', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_resources_table',
            },
        ),
    ]
