# Generated by Django 3.2.9 on 2021-12-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask_detect', '0006_user_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_resources',
            name='video_nums',
            field=models.IntegerField(default=0),
        ),
    ]
