# Generated by Django 3.2.9 on 2021-12-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mask_detect', '0007_alter_user_resources_video_nums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='used',
        ),
    ]
