# Generated by Django 3.2.9 on 2021-12-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask_detect', '0008_remove_camera_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='camera',
            name='desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
